/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecoracaoRouteImport } from './routes/decoracao'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as VelasRouteImport } from './routes/velas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoracaoRoute = DecoracaoRouteImport.update({
  id: '/decoracao',
  path: '/decoracao',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const VelasRoute = VelasRouteImport.update({
  id: '/velas',
  path: '/velas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decoracao': typeof DecoracaoRoute
  '/eventos': typeof EventosRoute
  '/velas': typeof VelasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decoracao': typeof DecoracaoRoute
  '/eventos': typeof EventosRoute
  '/velas': typeof VelasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decoracao': typeof DecoracaoRoute
  '/eventos': typeof EventosRoute
  '/velas': typeof VelasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decoracao' | '/eventos' | '/velas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decoracao' | '/eventos' | '/velas'
  id: '__root__' | '/' | '/decoracao' | '/eventos' | '/velas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecoracaoRoute: typeof DecoracaoRoute
  EventosRoute: typeof EventosRoute
  VelasRoute: typeof VelasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoracao': {
      id: '/decoracao'
      path: '/decoracao'
      fullPath: '/decoracao'
      preLoaderRoute: typeof DecoracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/velas': {
      id: '/velas'
      path: '/velas'
      fullPath: '/velas'
      preLoaderRoute: typeof VelasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecoracaoRoute: DecoracaoRoute,
  EventosRoute: EventosRoute,
  VelasRoute: VelasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
